#!/usr/bin/env python
import rospy as rp
from std_msgs.msg import Int32
from std_srvs.srv import Trigger
from py_ros_test_example.example_lib import Counter


def main():
    rp.init_node('py_ros_test_example_node')
    counter = Counter()

    def next_cb(req):
        counter.next()
        return {'success':True}

    def prev_cb(req):
        counter.previous()
        return {'success':True}

    next_srv = rp.Service("~next", Trigger, next_cb)

    prev_srv = rp.Service("~previous", Trigger, prev_cb)

    val_pub = rp.Publisher("~value", Int32, queue_size=10)

    rate = rp.Rate(5.0)

    while not rp.is_shutdown():
        val_pub.publish(data=int(counter.get()))
        rate.sleep()


if __name__ == '__main__':
    main()
